version: '3.7'

services:
  pangenome-node:
    container_name: pangenome-node
    image: pangenome-node
    build:
      context: ../..
      dockerfile: config/docker/node/Dockerfile
      args:
      - UID=${UID}
      - GID=${GID}
      - USER=${USER}
      - GROUP=${GROUP}
    volumes:
      - ../../.volumes/node/tmp:/tmp
      - ../../../aws_pangenome_dataset:/app/public/dataset:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UID=${UID}
      - GID=${GID}
      - USER=${USER}
      - GROUP=${GROUP}
      - TERM=xterm-256color
    restart: always
    init: true
    tty: true

  pangenome-nginx:
    depends_on:
      - pangenome-node
    container_name: pangenome-nginx
    image: pangenome-nginx
    build:
      context: ../..
      dockerfile: config/docker/nginx/Dockerfile
    volumes:
      - ../../.volumes/nginx/var/cache/nginx:/var/cache/nginx
      - ../../.volumes/nginx/var/lib/nginx/logs:/var/lib/nginx/logs
      - ../../.volumes/nginx/var/lib/letsencrypt:/var/lib/letsencrypt
      - ../../.volumes/nginx/var/log/letsencrypt:/var/log/letsencrypt
      - ../../.volumes/nginx/etc/letsencrypt:/etc/letsencrypt
      - ../../.volumes/nginx/www/letsencrypt:/www/letsencrypt
      - ../../.volumes/nginx/tmp:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:8080
      - 443:44443
    environment:
      - TERM=xterm-256color
    restart: always
    init: true
    tty: true
